apiVersion: apps/v1
Kind: Deployment
metadata:
  name: httpserver-deployment
  labels:
    app: httpserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
      - name: httpserver
        image: sinalvee/go-httpserver
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: '2'
            memory: 500Mi
          requests:
            cpu: '1'
            memory: 200Mi
        volumeMounts:
          - mountPath: /app/config.yaml
            name: httpserver-config
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sleep 2"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      volumes:
      - configMap:
          defaultMode: 420
          name: httpserver-config
        name: httpserver-config